### ISSUE TITLE
Switching back to lower resolution mode wasn't possible

### ISSUE THREAD

**Issue by dejanpan** [orosandrei/Home-Monitoring-Raspberry-Pi-Node#2]
There was a bug that would prevent going back to 480p once you switched to 720p (or back to 720p once you switched to 1080).

This should fix it: https://github.com/dejanpan/Home-Monitoring-Raspberry-Pi-Node/commit/94ebdc281c0cea1bdbd82afc0cba37cf1d5f9c85, however admitedly me being super newbie JS programmer there could be a better solution. 

If you like this one or if you tell me how you wonna have it I can provide a proper PR.

**Comment by orosandrei** [comment]
fixed https://github.com/orosandrei/Home-Monitoring-Raspberry-Pi-Node/commit/5f481176d9b47406095e1ca163dd31c5b9c23620 , thanks for pointing it out
